# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the local project files to the container
COPY . .

# Install required packages
RUN pip install .

# Expose any ports if necessary (e.g., for RPC services)
# EXPOSE 8000

# Command to run the observer script (adjust if needed)
CMD ["python", "src/app_api/deploy.py"]
