# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the local project files to the container
COPY . .

# Install required packages
RUN pip install .

# Expose any ports if necessary (e.g., for RPC services)
EXPOSE 3000

# Command to run the dummy node script (adjust if needed)
CMD ["python", "src/experiment_design/services/basic_split_inference.py"]
