FROM python:3.11 AS base

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY pnodelib/ ./
RUN pip install pnodelib/

CMD [ "python", "bin/rpyc_classic.py"]
