# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import colab_vision_pb2 as colab__vision__pb2


class colab_visionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.constantInference = channel.stream_stream(
                '/colab_vision/constantInference',
                request_serializer=colab__vision__pb2.Info_Chunk.SerializeToString,
                response_deserializer=colab__vision__pb2.Response_Dict.FromString,
                )


class colab_visionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def constantInference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_colab_visionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'constantInference': grpc.stream_stream_rpc_method_handler(
                    servicer.constantInference,
                    request_deserializer=colab__vision__pb2.Info_Chunk.FromString,
                    response_serializer=colab__vision__pb2.Response_Dict.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colab_vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class colab_vision(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def constantInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/colab_vision/constantInference',
            colab__vision__pb2.Info_Chunk.SerializeToString,
            colab__vision__pb2.Response_Dict.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
